name: Go
on: [push]
jobs:
  test:
    name: Run the unit test and build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: go test
        run:  |
          go get github.com/rainycape/unidecode
          go test .

      - name: Build
        run: go build -v .

      - name: github-action-publish-binaries
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
